### PR TITLE
updated cmake configurations

### PR DESCRIPTION
**Pull request by rxdu**
- There is no code change in this commit, only changes in CMake configuration files.
- Added ascent header-only library as an INTERFACE target. The benefit is that you don't have to use "include_directories" at multiple places with the hard-coded path in a CMake project to resolve header paths correctly. Use "target_link_libraries(<your-target> ascent)" to handle the dependency instead.

I know the way to configure CMake could be a personal preference matter. So feel free to reject the pull request if you don't feel it makes things better. 

Thanks for sharing your work.

### CODE REVIEW

**Comment by stephenberry** [comment]
Thanks for this change, I'm not very familiar to CMake and I was wanting this. I'm pulling your request.

**Comment by stephenberry** [comment]
One change I made from your pull request was to change the top level "ascent" folder name to "include". I hope this doesn't cause you any issues.

**Comment by rxdu** [comment]
That's no problem. In that way, I would suggest you keep the whole repo as a single project for simplicity, instead of the current "1 top-project + 3 sub-projects". Then it's more like a "standard" structure of a CMake project. Take a look at this branch to see what I meant:
https://github.com/rxdu/Ascent/tree/cmake_build

**Comment by stephenberry** [comment]
Thanks! I just updated the repository like yours, and added CMake options for building the examples or unit tests.

**Pull request merged**
